New Cvar: mp_drop_grenade_enable
rehlds/ReGameDLL_CS pull request #782
Opened 2022-10-12 18:01 UTC by JulioBarker

Allow players to drop grenades from their inventory

2022-10-14 16:39 UTC, StevenKal commented
I might recommend to put a CVar via flags in order to control the manual drop "per grenade", then put the CVar code inside each function "*::CanDrop".
Like I did for a module [here](https://www.amxmod.net/forum/showthread.php?tid=1583), so, more customizable.

2022-10-15 18:11 UTC, Vaqtincha commented
regame is slowly turning into a circus

2022-11-24 18:21 UTC, wopox1337 requested changes
Found bug

Desc: It is enough to press `G` after throwing this grenade, but before deploy new weapon. It will drop fake nade

https://www.youtube.com/watch?v=aE1eI4Yud1I

2022-11-24 21:03 UTC, Vaqtincha commented
Типичный шорох: мержит все что не проверено и бесполезное и не мержит правки которые тестировали 2-3 года.

2022-11-24 21:28 UTC, wopox1337 commented
@JulioBarker need changes

2022-11-25 05:36 UTC, Vaqtincha commented
then players will start spamming with grenades. and you will add another million cvars to control it. 

IMHO it's better to do this with 3rd party plugins.

2022-11-28 05:52 UTC, Vaqtincha commented
What else will happen if I have 2 flash? Will drop everything. Although it should be one at a time, but this requires an additional code.

2022-11-30 06:22 UTC, Vaqtincha commented
Шолох давай сюда умник.

2022-12-13 15:40 UTC, wopox1337 requested changes
still buggy with 2 flashes

2023-07-13 03:41 UTC, dystopm commented
IMO, this should be a 3rd party plugin. Idea is good, but:
1) Dropping grenade per grenade would spam world with entities (considering you can extend grenade carry limit), leading to (2)
2) If you have ammo > 1, then you'll drop a single grenade weaponbox containing +2 ammo on it, which is aesthetically uncomfortable, leading to (3)
3) Use a different model (ammo box maybe? something like models/w_argrenade.mdl) for grenade weaponboxes but only when ammo > 1, but that will turn this to an extra feature, and an extra model precaching, leading to go outside the limits of the purpose of this project.

2024-08-09 10:12 UTC, q52888940 commented
Why i can drop knife?????

2024-08-09 19:33 UTC, wopox1337 requested changes
check that https://github.com/s1lentq/ReGameDLL_CS/blob/c48be874743b2a440728889acb4797f4ec04137a/regamedll/dlls/player.cpp#L1578-L1589

2024-08-09 19:33 UTC, wopox1337 commented on regamedll/dlls/player.cpp
> +#endif
Check how `mp_nadedrops` works and redo the code to take into account the `weaponbox` requirements and player checks that are already there.

2024-08-09 19:41 UTC, Vaqtincha commented
Бесполезно. Зачем вообще бросать гранату на землю? Чтобы засорять карту флудом?

2024-08-09 20:16 UTC, StevenKal commented
And why talk in Russian when you can do efforts to talk in English!

> Бесполезно. Зачем вообще бросать гранату на землю? Чтобы засорять карту флудом?

And why talk in Russian when you can do efforts to talk in English! Still same shits with you!

2024-09-14 21:27 UTC, Vaqtincha commented
> > Бесполезно. Зачем вообще бросать гранату на землю? Чтобы засорять карту флудом?
> 
> And why talk in Russian when you can do efforts to talk in English! Still same shits with you!

Я тебя не ответил русофоб. Иди мимо пожалуйста.

2025-09-26 19:14 UTC, closed without merging